service: aws-node-scheduled-cron-project

frameworkVersion: '2'

# Uncomment if you want to use Serverless' built-in dotenv feature instead Note:
# Serverless will load all env vars in `.env` in 3.0.0+
# https://www.serverless.com/framework/docs/environment-variables/
# useDotenv: true
variablesResolutionMode: 20210219
configValidationMode: error
# Do this if you only want to load env vars into the Serverless environment
# This will make env vars available here and in any Serverless plugins
custom:
  dotenvVars: ${file(config.js)}

  

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    LOGOUT_EVT_NAME: ${self:custom.dotenvVars.LOGOUT_EVT_NAME}
functions:
  cronHandler:
    handler: handler.run
    role: myCustomRole
    events:
      - schedule:
          # careful double indent here
          name: ${self:custom.dotenvVars.LOGOUT_EVT_NAME}
          description: 'Some desc'
          rate: cron(0 0 1 1 ? 2020)
          enabled: true

resources:
  Resources:
    myCustomRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: MyCustomRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              #double indent??
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      # careful indents
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                # - Effect: Allow
                #   Action:
                #     - events:PutRule
                #   Resource: "*"
